[package]
name = "session-expiration-simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
fantoccini = "0.21.4"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.12", features = ["cookies"] }
serde_json = "1.0.137"
